on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select the Environment'
        type: choice
        required: true
        options:
        - SIT
        - UAT
        
jobs:
  test:
    steps:
      - name: testing
        run: echo " user input"
