on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select the Environment'
        type: choice
        required: true
        options:
        - UAT
        - SIT
      op:
        description: 'Deploy or Delete Apps'
        if: contains(inputs.env, 'SIT')
        type: choice
        
        options: # Only show options if 'SIT' is selected
         - Deploy
         - Delete
        
      
        
       
      
        
jobs:
  test:
    steps:
      - name: testing
        run: echo " user input"
