on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select the Environment'
        type: string
        required: true
        options:
        - UAT
           
        - SIT
            
      op:
        description: 'Deploy or Delete Apps'
        if: ${{ github.event.inputs.env, =='SIT')
        type: string
        required: false
        options: # Only show options if 'SIT' is selected
         - Deploy
         - Delete
        
      
        
       
      
        
jobs:
  test:
    steps:
      - name: testing
        run: echo " user input"
