on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select the Environment'
        type: choice
        required: true
        options:
        - SIT
        - UAT
      op:
        description: 'Deploy or Delete Apps'
        type: choice
        required: ${{contains('SIT', inputs.env)}}
      
        
jobs:
  test:
    steps:
      - name: testing
        run: echo " user input"
