on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select the Environment'
        type: choice
        required: true
        options:
        - SIT
        - UAT
      op:
        description: 'Deploy or Delete Apps'
        type: choice
        required: true
        options: # Only show options if 'SIT' is selected
        - Deploy
        - Delete
        
       
      
        
jobs:
  test:
    steps:
      - name: testing
        run: echo " user input"
